import { db } from './db';
import * as schema from '@shared/schema';

const upgrades = [
  // Accessories Parent (for variations)
  {
    id: "accessories-parent",
    name: "Accessories",
    category: "equipment",
    description: "Choose your equipment package - Maxi Euro 8 with T5000/T6000 Pro & Mini Spin",
    price: 114500,
    images: [],
    parentId: null,
    variantName: null,
    published: false,
  },
  {
    id: "accessories-pack-1",
    name: "Accessories Pack 1",
    category: "equipment",
    description: "Maxi Euro 8 with T5000 Pro & Mini Spin",
    price: 114500,
    images: [],
    parentId: "accessories-parent",
    variantName: "Pack 1 - Maxi Euro 8 with T5000 Pro & Mini Spin",
    published: true,
  },
  {
    id: "accessories-pack-2",
    name: "Accessories Pack 2",
    category: "equipment",
    description: "Euro 8 with T5000 Pro & Mini Spin",
    price: 114500,
    images: [],
    parentId: "accessories-parent",
    variantName: "Pack 2 - Euro 8 with T5000 Pro & Mini Spin",
    published: true,
  },
  {
    id: "accessories-pack-3",
    name: "Accessories Pack 3",
    category: "equipment",
    description: "Mini Euro 8 with T5000 Pro & Mini Spin",
    price: 114500,
    images: [],
    parentId: "accessories-parent",
    variantName: "Pack 3 - Mini Euro 8 with T5000 Pro & Mini Spin",
    published: true,
  },
  {
    id: "accessories-pack-4",
    name: "Accessories Pack 4",
    category: "equipment",
    description: "Maxi Euro 8 with T6000 Pro & Mini Spin",
    price: 114500,
    images: [],
    parentId: "accessories-parent",
    variantName: "Pack 4 - Maxi Euro 8 with T6000 Pro & Mini Spin",
    published: true,
  },

  // Air System Upgrades
  {
    id: "mounted-pto-air-system",
    name: "Mounted PTO Air System Upgrade",
    category: "air-systems",
    description: "Professional air system for mobile tyre fitting vehicles. We compound, powerful design for truly engineered for integrated into commercial vehicles",
    price: 449500,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
  },
  {
    id: "compressor-12hp-270l",
    name: "Compressor Upgrade To 12hp 270 Litre Electric Start",
    category: "air-systems",
    description: "HEAVY DUTY compressor pump only",
    price: 100000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
    popular: true,
  },
  {
    id: "air-reel-fini",
    name: "Fini 9 meter Air Reel With Built In Compressor",
    category: "air-systems",
    description: "Professional 9 meter air reel with built-in compressor",
    price: 54500,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
  },
  {
    id: "compressor-reel-16m",
    name: "16m Compressor Reel",
    category: "air-systems",
    description: "Keep your air line well and out Kay. With our compressor reel",
    price: 17500,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
  },

  // Equipment
  {
    id: "super-spin-upgrade",
    name: "Upgrade to Super Spin auto spin wheel balancer",
    category: "equipment",
    description: "",
    price: 45000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
  },

  // Branding
  {
    id: "full-revalco-wrap",
    name: "Full Revalco Wrap",
    category: "branding",
    description: "Give your van kerb appeal by having blowable full van wrap (LWB / MWB available)",
    price: 320000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
  },
  {
    id: "half-wrap",
    name: "Half Wrap",
    category: "branding",
    description: "Give your van the WOW factor with a half wrap",
    price: 180000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
  },
  {
    id: "graphic-pack",
    name: "Graphic Pack",
    category: "branding",
    description: "Add vehicle graphic pack (printed places on scores and rear, text on doors and rear sound)",
    price: 100000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
  },
  {
    id: "rear-chapter-livery",
    name: "Rear Chapter & Livery",
    category: "branding",
    description: "Make sure you are aware at the back of the road with our fluorescent yellow day chapter & kit",
    price: 45000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
  },
  {
    id: "branded-website",
    name: "Branded Website",
    category: "branding",
    description: "Have your very own branded website. Price is £1050+vat depending on your specification",
    price: 105000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
  },
  {
    id: "full-print-package",
    name: "Full Print Package",
    category: "branding",
    description: "500 Business cards, 250 Leaflets, 5 Social media setup (Max 2 platforms)",
    price: 55000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
  },
  {
    id: "garage-branding",
    name: "Garage Branding (Member of team will contact you for pricing)",
    category: "branding",
    description: "Reactivate branding: Graphic signage, Pivot, A Boards, banners",
    price: 1,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
  },

  // Van Interior Walls (with variations)
  {
    id: "van-interior-walls-parent",
    name: "Van Interior Walls",
    category: "comfort",
    description: "Line the interior of your van with white coating to protect your van",
    price: 160000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
  },
  {
    id: "van-interior-diamond-lwb-standard",
    name: "Van Interior Walls - Diamond Liner LWB Standard",
    category: "comfort",
    description: "Line the interior of your van with white coating to protect your van",
    price: 160000,
    images: [],
    parentId: "van-interior-walls-parent",
    variantName: "Diamond Liner - LWB Standard",
    published: true,
  },
  {
    id: "van-interior-diamond-lwb-branded",
    name: "Van Interior Walls - Diamond Liner LWB Branded",
    category: "comfort",
    description: "Line the interior of your van with white coating to protect your van - with branding",
    price: 160000,
    images: [],
    parentId: "van-interior-walls-parent",
    variantName: "Diamond Liner - LWB Branded",
    published: true,
  },

  // Security
  {
    id: "van-cctv-system",
    name: "Van Online CCTV/NVR System",
    category: "security",
    description: "Add extra security and peace of mind to your van with our online / offline CCTV system",
    price: 220000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
  },
  {
    id: "vehicle-immobiliser",
    name: "Vehicle Immobiliser",
    category: "security",
    description: "Most advanced vehicle immobiliser on the market to protect your business asset",
    price: 50000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
  },
  {
    id: "vehicle-tracker",
    name: "Vehicle tracker",
    category: "security",
    description: "With App to track your vehicle",
    price: 35000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
  },
  {
    id: "high-security-door-lock",
    name: "High Security Door Lock",
    category: "security",
    description: "Add extra security to your van with our high security locks",
    price: 19500,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
  },
  {
    id: "standard-reversing-camera",
    name: "Standard Reversing Camera Kit",
    category: "security",
    description: "Standard reversing camera with 7\" monitor",
    price: 49500,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
  },

  // Business
  {
    id: "business-package",
    name: "All you need business package",
    category: "business",
    description: "Website, Business cards, Leaflets, & Social media setup (Max 2 platforms)",
    price: 195000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
  },

  // Lighting Parent (with variations)
  {
    id: "light-pack-parent",
    name: "Light Pack",
    category: "lighting",
    description: "8 LED flashing repeaters, LED light bar to roof & working lights. With the optional upgrade you get LED scene lights",
    price: 120000,
    images: [],
    parentId: null,
    variantName: null,
    published: false,
  },
  {
    id: "light-pack-standard",
    name: "Standard Light Pack",
    category: "lighting",
    description: "8 LED flashing repeaters, LED light bar to roof & working lights",
    price: 120000,
    images: [],
    parentId: "light-pack-parent",
    variantName: "Standard Light Pack",
    published: true,
  },
  {
    id: "light-pack-upgraded",
    name: "Upgraded Light Pack",
    category: "lighting",
    description: "8 LED flashing repeaters, LED light bar to roof & working lights to side and rear of van. Upgraded to LED scene lights with side marker lights to side and rear",
    price: 170000,
    images: [],
    parentId: "light-pack-parent",
    variantName: "Upgraded Light Pack - LED Scene Lights",
    published: true,
  },

  // Technology
  {
    id: "remote-control",
    name: "Remote Control",
    category: "technology",
    description: "Control all of your vans accessories with our wireless remote system",
    price: 69500,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
  },
  {
    id: "monitor-brake-light-camera",
    name: "7\" Monitor With Brake Light Camera",
    category: "technology",
    description: "In cab 'plant' device always recording when driving",
    price: 49500,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
  },
  {
    id: "apple-carplay",
    name: "Apple CarPlay",
    category: "technology",
    description: "Apple CarPlay or Android Auto (vehicle dependent, starting from £650+vat, a member of our team will confirm that your ice vehicle package right, once order is placed)",
    price: 65000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
  },
  {
    id: "front-facing-dash-camera",
    name: "Front Facing Dash Camera",
    category: "technology",
    description: "In cab 'plant' device always recording when driving",
    price: 35000,
    images: [],
    parentId: null,
    variantName: null,
    published: true,
  },

  // Comfort Parent (Carpeted Ceiling with variations)
  {
    id: "carpeted-ceiling-parent",
    name: "Carpeted Ceiling",
    category: "comfort",
    description: "Carpeted ceiling for your van",
    price: 68500,
    images: [],
    parentId: null,
    variantName: null,
    published: false,
  },
  {
    id: "carpeted-ceiling-lwb-led",
    name: "Carpeted Ceiling LWB with LED cabin lights",
    category: "comfort",
    description: "",
    price: 68500,
    images: [],
    parentId: "carpeted-ceiling-parent",
    variantName: "LWB with LED cabin lights",
    published: true,
  },
];

async function seed() {
  console.log('Seeding upgrades...');
  
  for (const upgrade of upgrades) {
    await db.insert(schema.upgrades).values(upgrade).onConflictDoNothing();
  }
  
  console.log(`Successfully seeded ${upgrades.length} upgrades!`);
  process.exit(0);
}

seed().catch((err) => {
  console.error('Error seeding upgrades:', err);
  process.exit(1);
});
